local Scoreboard = loadfile("catvape/Libraries/Scoreboard/Scoreboard.lua")()
return {
	Start = function(mode, parent)
		Scoreboard:CreateScoreboard(parent)
		if mode:find("lobby") then
			Scoreboard:AddName("EASY.GG", Color3.fromRGB(255, 255, 0))
			Scoreboard:AddLine("date", "00/00/00", Color3.fromRGB(150, 150, 150))
			Scoreboard:AddLine("Empty1")
			Scoreboard:AddLine("level", "Level: <font color=\"rgb(202, 202, 202)\">0</font>")
			Scoreboard:AddLine("Empty2")
			Scoreboard:AddLine("progressText", "Progress: <font color=\"rgb(0, 255, 255)\">0</font><font color=\"rgb(202, 202, 202)\">/</font><font color=\"rgb(17, 255, 0)\">5k</font>")
			Scoreboard:AddLine("progressBar", "[<font color =\"rgb(202, 202, 202)\">■■■■■</font>]", Color3.fromRGB(150, 150, 150))
			Scoreboard:AddLine("Empty3")
			Scoreboard:AddLine("chests", "Loot Chests: <font color=\"rgb(225, 225, 0)\">0</font>")
			Scoreboard:AddLine("Empty4")
			Scoreboard:AddLine("coins", "Coins: <font color=\"rgb(239, 153, 14)\">0</font>")
			Scoreboard:AddLine("Empty5")
			Scoreboard:AddLine("kills", "Total Kills: <font color=\"rgb(17, 255, 0)\">0</font>")
			Scoreboard:AddLine("wins", "Total Wins: <font color=\"rgb(17, 255, 0)\">0</font>")
			Scoreboard:AddLine("Empty6")
			Scoreboard:AddLine("website", "www.easy.gg", Color3.fromRGB(255, 255, 0))
			Scoreboard:UpdateWidth(160)
		elseif mode:find("skywars") then
			Scoreboard:AddName("SKYWARS", Color3.fromRGB(255, 255, 0))
			Scoreboard:AddLine("date", "00/00/00", Color3.fromRGB(150, 150, 150))
			Scoreboard:AddLine("Empty1")
			Scoreboard:AddLine("eventText", "Next Event")
			Scoreboard:AddLine("eventInfo", "None", Color3.fromRGB(0, 255, 0))
			Scoreboard:AddLine("Empty2")
			Scoreboard:AddLine("players", "Players left: <font color=\"rgb(0, 255, 0)\">0</font>")
			Scoreboard:AddLine("Empty3")
			Scoreboard:AddLine("kills", "Kills: <font color=\"rgb(0, 255, 0)\">0</font>")
			Scoreboard:AddLine("Empty4")
			Scoreboard:AddLine("map", "Map: <font color=\"rgb(0, 255, 0)\">None</font>")
			Scoreboard:AddLine("mode", "Mode: <font color=\"rgb(255, 50, 50)\">Insane</font>")
			Scoreboard:AddLine("Empty6")
			Scoreboard:AddLine("website", "www.easy.gg", Color3.fromRGB(255, 255, 0))
			Scoreboard:UpdateWidth(160)
		elseif mode:find('to4') or mode:find("squads") then --> squad
			Scoreboard:AddName("BEDWARS", Color3.fromRGB(255, 255, 0))
			Scoreboard:AddLine("date", "00/00/00", Color3.fromRGB(150, 150, 150))
			Scoreboard:AddLine("Empty1")
			Scoreboard:AddLine("eventText", "Diamond Guardians:")
			Scoreboard:AddLine("eventInfo", "0:00", Color3.fromRGB(0, 255, 0))
			Scoreboard:AddLine("Empty2")
			Scoreboard:AddLine("Orange", "<b><font color=\"rgb(255, 0, 0)\">R</font></b> Red: <font color=\"rgb(0, 255, 0)\">✓</font>")
			Scoreboard:AddLine("Yellow", "<b><font color=\"rgb(255, 255, 0)\">Y</font></b> Yellow: <font color=\"rgb(0, 255, 0)\">✓</font>")
			Scoreboard:AddLine("Pink", "<b><font color=\"rgb(0, 255, 0)\">G</font></b> Green: <font color=\"rgb(0, 255, 0)\">✓</font>")
			Scoreboard:AddLine("Blue", "<b><font color=\"rgb(0, 0, 255)\">B</font></b> Blue: <font color=\"rgb(0, 255, 0)\">✓</font>")
			Scoreboard:AddLine("Empty3")
			Scoreboard:AddLine("kills", "Kills: <font color=\"rgb(0, 255, 0)\">0</font>")
			Scoreboard:AddLine("finalkills", "Final Kills: <font color=\"rgb(0, 255, 0)\">0</font>")
			Scoreboard:AddLine("Empty4")
			Scoreboard:AddLine("website", "www.easy.gg", Color3.fromRGB(255, 255, 0))
			Scoreboard:UpdateWidth(160)
		end
	end,
	Api = Scoreboard
}